package education.cccp.academy.installer

/**
 * Pure installer script generator (ACADEMY-1-1) — renders a deterministic,
 * per-target platform installer scaffold. No I/O, no Gradle types: a pure
 * function from [InstallerPlatform] to the distribution files.
 *
 * Scaffold contract (refined by the ACADEMY-6 cadrage per platform):
 *  - identity and pinned toolchain (Java Temurin + Gradle) are inlined
 *  - host bootstrap: Docker (Linux shell check / macOS Homebrew cask /
 *    Windows admin + PowerShell MSI)
 *  - idempotence marker so re-running the installer is a no-op
 *  - credentials are NEVER embedded: only the [InstallerPlatform.credentialsEnvPrefix]
 *    convention is documented, values flow through environment variables
 *  - the `docker-compose.yml` scaffold (Moodle + PostgreSQL + Ollama +
 *    Portainer) is embedded as a heredoc only when
 *    [InstallerPlatform.composeEnabled]; the opencode workspace service is
 *    deferred (TODO ACADEMY-5 — its image is not published yet)
 */
object InstallerScriptGenerator {

    /** Renders the single installer script for the given platform. */
    fun render(platform: InstallerPlatform): List<InstallerFile> {
        val content = when (platform.os) {
            TargetOs.LINUX -> linuxScript(platform)
            TargetOs.MACOS -> macosScript(platform)
            TargetOs.WINDOWS -> windowsScript(platform)
        }
        return listOf(InstallerFile(relativePath = platform.os.scriptName, content = content))
    }

    private fun linuxScript(platform: InstallerPlatform): String = buildString {
        appendLine("#!/usr/bin/env bash")
        appendLine("# ${platform.applicationName} installer scaffold - Linux (generated by education.cccp.academy)")
        appendLine("set -euo pipefail")
        appendLine()
        appendLine("APP_NAME=\"${platform.applicationName}\"")
        appendLine("APP_VERSION=\"${platform.applicationVersion}\"")
        appendLine("JAVA_VERSION=\"${platform.javaVersion}\"")
        appendLine("GRADLE_VERSION=\"${platform.gradleVersion}\"")
        appendLine("ENV_PREFIX=\"${platform.credentialsEnvPrefix}\"")
        appendLine("INSTALL_ROOT=\"\$HOME/.academy\"")
        appendLine("APP_DIR=\"\$INSTALL_ROOT/\$APP_NAME\"")
        appendLine()
        appendLine("# Idempotence guard")
        appendLine("if [ -f \"\$INSTALL_ROOT/.installed-\$APP_VERSION\" ]; then")
        appendLine("  echo \"[academy] \$APP_NAME \$APP_VERSION already installed\"")
        appendLine("  exit 0")
        appendLine("fi")
        appendLine()
        appendLine("# Host bootstrap: Docker engine")
        appendLine("if ! command -v docker >/dev/null 2>&1; then")
        appendLine("  echo \"[academy] Docker is required - install it first (https://docs.docker.com/engine/install/)\"")
        appendLine("  exit 1")
        appendLine("fi")
        appendLine()
        appendLine("# Provision Java Temurin")
        appendLine("mkdir -p \"\$INSTALL_ROOT/jdk\"")
        appendLine("echo \"[academy] provisioning Java Temurin \$JAVA_VERSION...\"")
        appendLine("if [ ! -f \"\$INSTALL_ROOT/jdk/.ready-\$JAVA_VERSION\" ]; then")
        appendLine("  curl -fsSL -o /tmp/jdk.tar.gz \"https://github.com/adoptium/temurin\$JAVA_VERSION-binaries/releases/latest/download/OpenJDK\$JAVA_VERSION-jdk_x64_linux_hotspot.tar.gz\"")
        appendLine("  tar -xzf /tmp/jdk.tar.gz -C \"\$INSTALL_ROOT/jdk\" --strip-components=1")
        appendLine("  touch \"\$INSTALL_ROOT/jdk/.ready-\$JAVA_VERSION\"")
        appendLine("fi")
        appendLine("export JAVA_HOME=\"\$INSTALL_ROOT/jdk\"")
        appendLine("export PATH=\"\$JAVA_HOME/bin:\$PATH\"")
        appendLine()
        appendLine("# Provision Gradle")
        appendLine("echo \"[academy] provisioning Gradle \$GRADLE_VERSION...\"")
        appendLine("if [ ! -d \"\$INSTALL_ROOT/gradle/gradle-\$GRADLE_VERSION\" ]; then")
        appendLine("  curl -fsSL -o /tmp/gradle.zip \"https://services.gradle.org/distributions/gradle-\$GRADLE_VERSION-bin.zip\"")
        appendLine("  mkdir -p \"\$INSTALL_ROOT/gradle\"")
        appendLine("  unzip -q /tmp/gradle.zip -d \"\$INSTALL_ROOT/gradle\"")
        appendLine("fi")
        appendLine("export PATH=\"\$INSTALL_ROOT/gradle/gradle-\$GRADLE_VERSION/bin:\$PATH\"")
        appendLine()
        appendComposeScaffold(platform)
        appendLine("# Credentials flow through the environment: export \${ENV_PREFIX}* before provisioning")
        appendLine("echo \"[academy] read credentials from \${ENV_PREFIX}* environment variables\"")
        appendLine()
        appendLine("touch \"\$INSTALL_ROOT/.installed-\$APP_VERSION\"")
        appendLine("echo \"[academy] \$APP_NAME \$APP_VERSION installed - provision and start the academy workspace\"")
    }

    private fun macosScript(platform: InstallerPlatform): String = buildString {
        appendLine("#!/usr/bin/env bash")
        appendLine("# ${platform.applicationName} installer scaffold - macOS (generated by education.cccp.academy)")
        appendLine("set -euo pipefail")
        appendLine()
        appendLine("APP_NAME=\"${platform.applicationName}\"")
        appendLine("APP_VERSION=\"${platform.applicationVersion}\"")
        appendLine("JAVA_VERSION=\"${platform.javaVersion}\"")
        appendLine("GRADLE_VERSION=\"${platform.gradleVersion}\"")
        appendLine("ENV_PREFIX=\"${platform.credentialsEnvPrefix}\"")
        appendLine("INSTALL_ROOT=\"\$HOME/.academy\"")
        appendLine("APP_DIR=\"\$INSTALL_ROOT/\$APP_NAME\"")
        appendLine("ARCH=\"\$(uname -m)\"")
        appendLine()
        appendLine("# Idempotence guard")
        appendLine("if [ -f \"\$INSTALL_ROOT/.installed-\$APP_VERSION\" ]; then")
        appendLine("  echo \"[academy] \$APP_NAME \$APP_VERSION already installed\"")
        appendLine("  exit 0")
        appendLine("fi")
        appendLine()
        appendLine("# Host bootstrap: Homebrew + Docker Desktop")
        appendLine("if ! command -v brew >/dev/null 2>&1; then")
        appendLine("  echo \"[academy] Homebrew is required - see https://brew.sh\"")
        appendLine("  exit 1")
        appendLine("fi")
        appendLine("brew install --cask docker")
        appendLine("open -a Docker")
        appendLine()
        appendLine("# Provision Java Temurin via Homebrew")
        appendLine("brew install \"openjdk@\$JAVA_VERSION\"")
        appendLine("export JAVA_HOME=\"\$(brew --prefix)/opt/openjdk@\$JAVA_VERSION/libexec/openjdk.jdk/Contents/Home\"")
        appendLine("export PATH=\"\$JAVA_HOME/bin:\$PATH\"")
        appendLine()
        appendLine("# Provision Gradle")
        appendLine("brew install gradle --version \"\$GRADLE_VERSION\" || brew install gradle")
        appendLine()
        appendComposeScaffold(platform)
        appendLine("# Credentials flow through the environment: export \${ENV_PREFIX}* before provisioning")
        appendLine("echo \"[academy] read credentials from \${ENV_PREFIX}* environment variables\"")
        appendLine()
        appendLine("touch \"\$INSTALL_ROOT/.installed-\$APP_VERSION\"")
        appendLine("echo \"[academy] \$APP_NAME \$APP_VERSION installed - provision and start the academy workspace\"")
    }

    private fun windowsScript(platform: InstallerPlatform): String = buildString {
        appendLine("@echo off")
        appendLine("rem ${platform.applicationName} installer scaffold - Windows (generated by education.cccp.academy)")
        appendLine("setlocal")
        appendLine("set APP_NAME=${platform.applicationName}")
        appendLine("set APP_VERSION=${platform.applicationVersion}")
        appendLine("set JAVA_VERSION=${platform.javaVersion}")
        appendLine("set GRADLE_VERSION=${platform.gradleVersion}")
        appendLine("set ENV_PREFIX=${platform.credentialsEnvPrefix}")
        appendLine("set INSTALL_ROOT=%USERPROFILE%\\.academy")
        appendLine("set APP_DIR=%INSTALL_ROOT%\\%APP_NAME%")
        appendLine()
        appendLine("rem Admin rights check")
        appendLine("net session >nul 2>&1")
        appendLine("if errorlevel 1 (")
        appendLine("  echo [academy] Administrator rights required")
        appendLine("  exit /b 1")
        appendLine(")")
        appendLine()
        appendLine("rem Idempotence guard")
        appendLine("if exist \"%INSTALL_ROOT%\\.installed-%APP_VERSION%\" (")
        appendLine("  echo [academy] %APP_NAME% %APP_VERSION% already installed")
        appendLine("  exit /b 0")
        appendLine(")")
        appendLine()
        appendLine("rem Host bootstrap: Docker Desktop")
        appendLine("PowerShell -Command \"if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { Write-Error 'Docker Desktop is required - install it first (https://www.docker.com/products/docker-desktop/)'; exit 1 }\"")
        appendLine()
        appendLine("rem Provision Java Temurin")
        appendLine("PowerShell -Command \"Invoke-WebRequest -Uri 'https://api.adoptium.net/v3/binary/latest/%JAVA_VERSION%/ga/windows/x64/jdk/hotspot/normal/eclipse' -OutFile '%TEMP%\\jdk.zip'; Expand-Archive -Path '%TEMP%\\jdk.zip' -DestinationPath '%INSTALL_ROOT%\\jdk' -Force\"")
        appendLine("setx JAVA_HOME \"%INSTALL_ROOT%\\jdk\" >nul")
        appendLine("setx PATH \"%INSTALL_ROOT%\\jdk\\bin;%PATH%\" >nul")
        appendLine()
        appendLine("rem Provision Gradle")
        appendLine("PowerShell -Command \"Invoke-WebRequest -Uri 'https://services.gradle.org/distributions/gradle-%GRADLE_VERSION%-bin.zip' -OutFile '%TEMP%\\gradle.zip'; Expand-Archive -Path '%TEMP%\\gradle.zip' -DestinationPath '%INSTALL_ROOT%\\gradle' -Force\"")
        appendLine("setx PATH \"%INSTALL_ROOT%\\gradle\\gradle-%GRADLE_VERSION%\\bin;%PATH%\" >nul")
        appendLine()
        appendWindowsComposeScaffold(platform)
        appendLine("rem Credentials flow through the environment: set %ENV_PREFIX%* before provisioning")
        appendLine("echo [academy] %APP_NAME% %APP_VERSION% installed - provision and start the academy workspace")
        appendLine("endlocal")
    }

    /**
     * Canonical `docker-compose.yml` body shared by every platform (D-ACADEMY-6-5)
     * — the single source of truth that guarantees cross-platform parity: the
     * bash heredoc and the batch echo writer both render exactly these lines.
     *
     * It is complete and directly executable: dedicated network, named
     * persistent volumes, port mappings (Moodle 8080, Ollama 11434, Portainer
     * 9000), healthchecks (PostgreSQL `pg_isready`, Ollama — Portainer is
     * distroless and carries no healthcheck, D-ACADEMY-6-17), Moodle
     * wired to PostgreSQL via the real image contract (D-ACADEMY-6-14/15 —
     * `DB_TYPE`/`DB_HOST`/`DB_NAME`/`DB_USER`/`DB_PASS` +
     * `MOODLE_USERNAME`/`MOODLE_PASSWORD`/`MOODLE_SITENAME`) and values sourced
     * from `.env` — never embedded.
     */
    private fun composeBody(): List<String> = listOf(
        "services:",
        "  moodle:",
        "    image: erseco/alpine-moodle:v5.2.3",
        "    ports:",
        "      - \"8080:8080\"",
        "    environment:",
        "      DB_TYPE: pgsql",
        "      DB_HOST: postgres",
        "      DB_NAME: \${POSTGRES_DB}",
        "      DB_USER: postgres",
        "      DB_PASS: \${POSTGRES_PASSWORD}",
        "      MOODLE_USERNAME: \${MOODLE_USERNAME}",
        "      MOODLE_PASSWORD: \${MOODLE_PASSWORD}",
        "      MOODLE_SITENAME: \${MOODLE_SITENAME}",
        "    depends_on:",
        "      postgres:",
        "        condition: service_healthy",
        "    networks:",
        "      - academy-net",
        "  # TODO ACADEMY-5: add the opencode workspace service once its image is published",
        "  postgres:",
        "    image: postgres:16",
        "    environment:",
        "      POSTGRES_DB: \${POSTGRES_DB}",
        "      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}",
        "    volumes:",
        "      - postgres-data:/var/lib/postgresql/data",
        "    healthcheck:",
        "      test: [\"CMD-SHELL\", \"pg_isready -U postgres\"]",
        "      interval: 10s",
        "      timeout: 5s",
        "      retries: 5",
        "    networks:",
        "      - academy-net",
        "  ollama:",
        "    image: ollama/ollama",
        "    volumes:",
        "      - ollama-models:/root/.ollama",
        "    ports:",
        "      - \"11434:11434\"",
        "    healthcheck:",
        "      test: [\"CMD\", \"ollama\", \"list\"]",
        "      interval: 30s",
        "      timeout: 10s",
        "      retries: 3",
        "    networks:",
        "      - academy-net",
        "  portainer:",
        "    image: portainer/portainer-ce",
        "    ports:",
        "      - \"9000:9000\"",
        "    volumes:",
        "      - portainer-data:/data",
        "      - \"/var/run/docker.sock:/var/run/docker.sock\"",
        "    networks:",
        "      - academy-net",
        "  moodle-seed:",
        "    image: postgres:16",
        "    restart: \"no\"",
        "    entrypoint: [\"sh\", \"/seed/seed.sh\"]",
        "    environment:",
        "      PGHOST: postgres",
        "      PGDATABASE: \${POSTGRES_DB}",
        "      PGUSER: postgres",
        "      PGPASSWORD: \${POSTGRES_PASSWORD}",
        "    volumes:",
        "      - \"./seed:/seed\"",
        "    depends_on:",
        "      postgres:",
        "        condition: service_healthy",
        "    networks:",
        "      - academy-net",
        "",
        "networks:",
        "  academy-net:",
        "    driver: bridge",
        "",
        "volumes:",
        "  postgres-data:",
        "  ollama-models:",
        "  portainer-data:",
    )

    /**
     * `.env` body — documents the runtime configuration **names only**; values
     * are provided by the learner at runtime and never committed (Secrets rule,
     * D-ACADEMY-6-5). `POSTGRES_PASSWORD` is intentionally left empty.
     */
    private fun envBody(): List<String> = listOf(
        "# Academy runtime configuration - names only, values are provided at runtime (never committed)",
        "POSTGRES_DB=moodle",
        "POSTGRES_USER=postgres",
        "POSTGRES_PASSWORD=",
        "MOODLE_USERNAME=admin",
        "MOODLE_PASSWORD=",
        "MOODLE_SITENAME=Academy",
        "OLLAMA_HOST=http://ollama:11434",
    )

    /**
     * Seed entrypoint body (D-ACADEMY-6-6) — the single source of truth shared
     * by every platform. The one-shot `moodle-seed` service runs it on the first
     * `compose up`: it polls until Moodle has created its schema (`mdl_course`)
     * then applies [seedCourseSqlBody]. It never migrates, never deletes.
     *
     * The value of `PGPASSWORD` is read from the environment at runtime — this
     * scaffold embeds the convention only, never a secret.
     */
    private fun seedScriptBody(): List<String> = listOf(
        "#!/bin/sh",
        "# Academy Moodle seed entrypoint - idempotent, data-only (D-ACADEMY-6-6)",
        "set -eu",
        "echo \"[academy] waiting for the Moodle schema (mdl_course)...\"",
        "attempt=0",
        "until psql -tAc \"SELECT to_regclass('public.mdl_course')\" 2>&1 | grep -q mdl_course; do",
        "  attempt=\$((attempt + 1))",
        "  if [ \"\$attempt\" -ge 60 ]; then",
        "    echo \"[academy] Moodle schema not ready after 60 attempts - aborting seed\"",
        "    exit 1",
        "  fi",
        "  sleep 5",
        "done",
        "echo \"[academy] applying data-only course seed...\"",
        "psql -v ON_ERROR_STOP=1 -f /seed/seed-course.sql",
        "echo \"[academy] course seed applied (idempotent)\"",
    )

    /**
     * Minimal course seed SQL (D-ACADEMY-6-6) — **data-only and idempotent**:
     * a single `INSERT ... WHERE NOT EXISTS` keyed by a stable `idnumber`, so
     * running it twice is a no-op. No `DDL`, no `DELETE`, no `UPDATE`.
     */
    private fun seedCourseSqlBody(): List<String> = listOf(
        "-- Academy minimal course seed - data-only, idempotent (D-ACADEMY-6-6)",
        "-- The course lives in the default category (id 1) created by Moodle install.",
        "INSERT INTO mdl_course (",
        "  category, sortorder, fullname, shortname, idnumber, summary, summaryformat,",
        "  format, showgrades, newsitems, startdate, enddate, visible, groupmode,",
        "  groupmodeforce, defaultgroupingid, lang, timecreated, timemodified,",
        "  enablecompletion, showactivitydates, showcompletionconditions, requested",
        ")",
        "SELECT 1, 0, 'Academy - Experimentation Track', 'academy-seed', 'academy-seed',",
        "       'Minimal Moodle course seeded by the academy installer.', 1,",
        "       'topics', 1, 0, 0, 0, 1, 0,",
        "       0, 0, 'en', extract(epoch FROM now())::bigint, extract(epoch FROM now())::bigint,",
        "       1, 1, 1, 0",
        "WHERE NOT EXISTS (",
        "  SELECT 1 FROM mdl_course WHERE idnumber = 'academy-seed'",
        ");",
    )

    private fun StringBuilder.appendComposeScaffold(platform: InstallerPlatform) {
        if (!platform.composeEnabled) return
        appendLine("mkdir -p \"\$APP_DIR\"")
        appendLine("echo \"[academy] writing docker-compose.yml scaffold...\"")
        appendLine("cat > \"\$APP_DIR/docker-compose.yml\" <<'EOF'")
        composeBody().forEach { appendLine(it) }
        appendLine("EOF")
        appendLine("cat > \"\$APP_DIR/.env\" <<'EOF'")
        envBody().forEach { appendLine(it) }
        appendLine("EOF")
        appendLine("mkdir -p \"\$APP_DIR/seed\"")
        appendLine("cat > \"\$APP_DIR/seed/seed.sh\" <<'EOF'")
        seedScriptBody().forEach { appendLine(it) }
        appendLine("EOF")
        appendLine("cat > \"\$APP_DIR/seed/seed-course.sql\" <<'EOF'")
        seedCourseSqlBody().forEach { appendLine(it) }
        appendLine("EOF")
        appendLine("echo \"[academy] compose scaffold written - edit \$APP_DIR/.env and \$APP_DIR/docker-compose.yml before running docker compose up\"")
    }

    private fun StringBuilder.appendWindowsComposeScaffold(platform: InstallerPlatform) {
        if (!platform.composeEnabled) return
        appendLine("rem Compose scaffold")
        appendLine("if not exist \"%APP_DIR%\" mkdir \"%APP_DIR%\"")
        appendLine("> \"%APP_DIR%\\docker-compose.yml\" (")
        composeBody().forEach { appendLine("echo $it") }
        appendLine(")")
        appendLine("> \"%APP_DIR%\\.env\" (")
        envBody().forEach { appendLine("echo $it") }
        appendLine(")")
        appendLine("if not exist \"%APP_DIR%\\seed\" mkdir \"%APP_DIR%\\seed\"")
        appendLine("> \"%APP_DIR%\\seed\\seed.sh\" (")
        seedScriptBody().forEach { appendLine("echo ${escapeCmd(it)}") }
        appendLine(")")
        appendLine("> \"%APP_DIR%\\seed\\seed-course.sql\" (")
        seedCourseSqlBody().forEach { appendLine("echo ${escapeCmd(it)}") }
        appendLine(")")
        appendLine("rem Edit %APP_DIR%\\.env and %APP_DIR%\\docker-compose.yml before running docker compose up")
    }

    /**
     * Escapes the cmd metacharacters that are special inside a batch
     * `> file (` block: `^` `>` `&` `|` `(` `)`. Required so a line redirecting
     * stderr (`2>&1`) or calling a SQL function (`to_regclass(...)`) is echoed
     * literally by the Windows writer — the caret is consumed by cmd and the
     * written file keeps the original character.
     */
    private fun escapeCmd(line: String): String = line
        .replace("^", "^^")
        .replace(">", "^>")
        .replace("&", "^&")
        .replace("(", "^(")
        .replace(")", "^)")
}