package education.cccp.academy.installer

import education.cccp.academy.byok.ByokProviderCatalog
import education.cccp.academy.material.MaterialGuideGenerator
import education.cccp.academy.moodle.MoodleIngestionScriptGenerator
import education.cccp.academy.opencode.LearnerGuideGenerator
import education.cccp.academy.opencode.OpenCodeConfigGenerator
import education.cccp.academy.opencode.WorkspaceDockerfileGenerator

/**
 * Pure installer script generator (ACADEMY-1-1) — renders a deterministic,
 * per-target platform installer scaffold. No I/O, no Gradle types: a pure
 * function from [InstallerPlatform] to the distribution files.
 *
 * Scaffold contract (refined by the ACADEMY-6 cadrage per platform):
 *  - identity and pinned toolchain (Java Temurin + Gradle) are inlined as
 *    declared constants — the toolchain lives in the workspace image, it is
 *    never installed on the host (D-ACADEMY-6-10)
 *  - host bootstrap: Docker is the ONLY host requirement (Linux/macOS shell
 *    check / Windows admin + PowerShell check)
 *  - idempotence marker (versioned) so re-running the installer is a no-op
 *  - credentials are NEVER embedded: only the [InstallerPlatform.credentialsEnvPrefix]
 *    convention is documented, values flow through environment variables
 *  - the `docker-compose.yml` scaffold (Moodle + PostgreSQL + Ollama +
 *    Portainer) is embedded as a heredoc only when
 *    [InstallerPlatform.composeEnabled]; the opencode workspace service and
 *    its `opencode.json` are deferred (TODO ACADEMY-5 — image not published)
 */
object InstallerScriptGenerator {

    /** Renders the single installer script for the given platform. */
    fun render(platform: InstallerPlatform): List<InstallerFile> {
        val content = when (platform.os) {
            TargetOs.LINUX, TargetOs.MACOS -> unixScript(platform)
            TargetOs.WINDOWS -> windowsScript(platform)
        }
        return listOf(InstallerFile(relativePath = platform.os.scriptName, content = content))
    }

    /**
     * One portable Unix installer for Linux **and** macOS (D-ACADEMY-12-5): only
     * the OS-specific engine bootstrap differs, the compose/seed/env queue is
     * shared verbatim ([appendComposeScaffold]) — no duplication, structural
     * parity by construction.
     *
     * Linux provisions the native Docker Engine from Docker's official apt
     * repository; macOS provisions Colima (MIT) via Homebrew. Both then speak the
     * same `docker` + `docker compose` CLI (matrix D-ACADEMY-12-1).
     */
    private fun unixScript(platform: InstallerPlatform): String = buildString {
        val label = if (platform.os == TargetOs.MACOS) "macOS" else "Linux"
        appendLine("#!/usr/bin/env bash")
        appendLine("# ${platform.applicationName} installer scaffold - $label (generated by education.cccp.academy)")
        appendLine("set -euo pipefail")
        appendLine()
        appendLine("APP_NAME=\"${platform.applicationName}\"")
        appendLine("APP_VERSION=\"${platform.applicationVersion}\"")
        appendLine("# Pinned toolchain — provided by the workspace image, never installed on the host (D-ACADEMY-6-10)")
        appendLine("JAVA_VERSION=\"${platform.javaVersion}\"")
        appendLine("GRADLE_VERSION=\"${platform.gradleVersion}\"")
        appendLine("ENV_PREFIX=\"${platform.credentialsEnvPrefix}\"")
        appendLine("INSTALL_ROOT=\"\$HOME/.academy\"")
        appendLine("APP_DIR=\"\$INSTALL_ROOT/\$APP_NAME\"")
        if (platform.os == TargetOs.MACOS) {
            appendLine("ARCH=\"\$(uname -m)\"")
        }
        appendLine()
        appendLine("# Idempotence guard (versioned marker: a version bump re-provisions)")
        appendLine("if [ -f \"\$INSTALL_ROOT/.installed-\$APP_VERSION\" ]; then")
        appendLine("  echo \"[academy] \$APP_NAME \$APP_VERSION already installed\"")
        appendLine("  exit 0")
        appendLine("fi")
        appendLine()
        if (platform.os == TargetOs.MACOS) {
            appendMacosEngineBootstrap()
        } else {
            appendLinuxEngineBootstrap()
        }
        appendLine()
        appendComposeScaffold(platform)
        appendLine("# Credentials flow through the environment: export \${ENV_PREFIX}* before provisioning")
        appendLine("echo \"[academy] read credentials from \${ENV_PREFIX}* environment variables\"")
        appendLine()
        appendLine("touch \"\$INSTALL_ROOT/.installed-\$APP_VERSION\"")
        appendLine("echo \"[academy] \$APP_NAME \$APP_VERSION installed - provision and start the academy workspace\"")
    }

    /**
     * Linux engine bootstrap (D-ACADEMY-12-1) — the native Docker Engine from
     * Docker's official apt repository, exactly as documented at
     * `docs.docker.com/engine/install/{ubuntu,debian}/` (verified S-015): GPG key,
     * signed repository, then the five packages `docker-ce`, `docker-ce-cli`,
     * `containerd.io`, `docker-buildx-plugin`, `docker-compose-plugin`.
     *
     * Provisioning is guarded by the engine presence: a host that already speaks
     * `docker` is left untouched (idempotent, economy of motion).
     */
    private fun StringBuilder.appendLinuxEngineBootstrap() {
        appendLine("# Host bootstrap: provision the native Docker Engine when absent (D-ACADEMY-12-1)")
        appendLine("if ! command -v docker >/dev/null 2>&1; then")
        appendLine("  echo \"[academy] provisioning the Docker Engine from Docker's official apt repository...\"")
        appendLine("  DISTRO_ID=\"\$(. /etc/os-release && echo \"\$ID\")\"")
        appendLine("  CODENAME=\"\$(. /etc/os-release && echo \"\${UBUNTU_CODENAME:-\$VERSION_CODENAME}\")\"")
        appendLine("  case \"\$DISTRO_ID\" in")
        appendLine("    debian) DOCKER_REPO=\"debian\" ;;")
        appendLine("    *) DOCKER_REPO=\"ubuntu\" ;;")
        appendLine("  esac")
        appendLine("  sudo apt-get update")
        appendLine("  sudo apt-get install -y ca-certificates curl")
        appendLine("  sudo install -m 0755 -d /etc/apt/keyrings")
        appendLine("  sudo curl -fsSL \"https://download.docker.com/linux/\$DOCKER_REPO/gpg\" -o /etc/apt/keyrings/docker.asc")
        appendLine("  sudo chmod a+r /etc/apt/keyrings/docker.asc")
        appendLine("  echo \"deb [arch=\$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/\$DOCKER_REPO \$CODENAME stable\" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null")
        appendLine("  sudo apt-get update")
        appendLine("  sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin")
        appendLine("fi")
        appendLine("echo \"[academy] Docker detected - the toolchain lives in the workspace image (Java \$JAVA_VERSION, Gradle \$GRADLE_VERSION)\"")
    }

    /**
     * macOS engine bootstrap (D-ACADEMY-12-1) — Colima (MIT) instead of Docker
     * Desktop: Docker Engine needs a Linux kernel, so a VM is unavoidable on
     * macOS; Colima provides it for free while exposing the standard `docker`
     * CLI. Requires Homebrew; never sudo.
     */
    private fun StringBuilder.appendMacosEngineBootstrap() {
        appendLine("# Host bootstrap: provision Colima when absent (D-ACADEMY-12-1)")
        appendLine("if ! command -v docker >/dev/null 2>&1; then")
        appendLine("  echo \"[academy] provisioning Colima and the docker CLI via Homebrew...\"")
        appendLine("  if ! command -v brew >/dev/null 2>&1; then")
        appendLine("    echo \"[academy] Homebrew is required - see https://brew.sh\"")
        appendLine("    exit 1")
        appendLine("  fi")
        appendLine("  brew install colima docker")
        appendLine("  colima start")
        appendLine("fi")
        appendLine("echo \"[academy] Docker detected - the toolchain lives in the workspace image (Java \$JAVA_VERSION, Gradle \$GRADLE_VERSION)\"")
    }

    /**
     * Windows installer (D-ACADEMY-12-1/12-4) — provisions Docker Desktop, whose
     * Linux backend is WSL2.
     *
     * Facts are probed first (`net session` for admin, `wsl --status` for WSL2),
     * then the decision is explicit and resumable:
     *  - WSL2 present → install Docker Desktop per-user (`install --user --quiet
     *    --accept-license --backend=wsl-2`, no admin needed)
     *  - WSL2 absent, admin → `wsl --install` (a reboot may be required; the
     *    installer is resumable — never promise a reboot-free run, D-ACADEMY-12-4)
     *  - WSL2 absent, no admin → an explicit message (a verdict, never a silent
     *    failure)
     */
    private fun windowsScript(platform: InstallerPlatform): String = buildString {
        appendLine("@echo off")
        appendLine("rem ${platform.applicationName} installer scaffold - Windows (generated by education.cccp.academy)")
        appendLine("setlocal")
        appendLine("set APP_NAME=${platform.applicationName}")
        appendLine("set APP_VERSION=${platform.applicationVersion}")
        appendLine("rem Pinned toolchain - provided by the workspace image, never installed on the host (D-ACADEMY-6-10)")
        appendLine("set JAVA_VERSION=${platform.javaVersion}")
        appendLine("set GRADLE_VERSION=${platform.gradleVersion}")
        appendLine("set ENV_PREFIX=${platform.credentialsEnvPrefix}")
        appendLine("set INSTALL_ROOT=%USERPROFILE%\\.academy")
        appendLine("set APP_DIR=%INSTALL_ROOT%\\%APP_NAME%")
        appendLine("set IS_ADMIN=0")
        appendLine()
        appendLine("rem Idempotence guard (versioned marker: a version bump re-provisions)")
        appendLine("if exist \"%INSTALL_ROOT%\\.installed-%APP_VERSION%\" (")
        appendLine("  echo [academy] %APP_NAME% %APP_VERSION% already installed")
        appendLine("  exit /b 0")
        appendLine(")")
        appendLine()
        appendLine("rem Probe administrator rights - needed only to enable WSL2 (D-ACADEMY-12-4)")
        appendLine("net session >nul 2>&1")
        appendLine("if not errorlevel 1 set IS_ADMIN=1")
        appendLine()
        appendLine("rem Probe WSL2 presence - Docker Desktop's Linux backend")
        appendLine("wsl --status >nul 2>&1")
        appendLine("if errorlevel 1 goto bootstrap_wsl2")
        appendLine("goto install_docker_desktop")
        appendLine()
        appendLine(":bootstrap_wsl2")
        appendLine("if \"%IS_ADMIN%\"==\"1\" (")
        appendLine("  echo [academy] enabling WSL2 - a reboot may be required")
        appendLine("  wsl --install")
        appendLine("  echo [academy] WSL2 setup started - reboot if asked, then re-run this installer, it is resumable")
        appendLine("  exit /b 0")
        appendLine(")")
        appendLine("echo [academy] WSL2 is required for Linux containers and enabling it needs administrator rights - re-run as administrator")
        appendLine("exit /b 1")
        appendLine()
        appendLine(":install_docker_desktop")
        appendLine("rem Host bootstrap: provision Docker Desktop for the Linux backend when absent (D-ACADEMY-12-1)")
        appendLine("PowerShell -Command \"if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { \$f=Join-Path \$env:TEMP 'DockerDesktopInstaller.exe'; Invoke-WebRequest -Uri 'https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe' -OutFile \$f; Start-Process \$f -Wait -ArgumentList 'install','--user','--quiet','--accept-license','--backend=wsl-2' }\"")
        appendLine("if errorlevel 1 exit /b 1")
        appendLine("echo [academy] Docker detected - the toolchain lives in the workspace image (Java %JAVA_VERSION%, Gradle %GRADLE_VERSION%)")
        appendLine()
        appendWindowsComposeScaffold(platform)
        appendLine("rem Credentials flow through the environment: set %ENV_PREFIX%* before provisioning")
        appendLine("echo [academy] %APP_NAME% %APP_VERSION% installed - provision and start the academy workspace")
        appendLine("endlocal")
    }

    /**
     * Canonical `docker-compose.yml` body shared by every platform (D-ACADEMY-6-5)
     * — the single source of truth that guarantees cross-platform parity: the
     * bash heredoc and the batch echo writer both render exactly these lines.
     *
     * It is complete and directly executable: dedicated network, named
     * persistent volumes, port mappings (Moodle 8080, Ollama 11434, Portainer
     * 9000), healthchecks (PostgreSQL `pg_isready`, Ollama — Portainer is
     * distroless and carries no healthcheck, D-ACADEMY-6-17), Moodle
     * wired to PostgreSQL via the real image contract (D-ACADEMY-6-14/15 —
     * `DB_TYPE`/`DB_HOST`/`DB_NAME`/`DB_USER`/`DB_PASS` +
     * `MOODLE_USERNAME`/`MOODLE_PASSWORD`/`MOODLE_SITENAME`) and values sourced
     * from `.env` — never embedded.
     */
    private fun composeBody(platform: InstallerPlatform): List<String> {
        val workspaceEnv = mutableListOf("      OLLAMA_HOST: \${OLLAMA_HOST}")
        workspaceKeyEnvVar(platform)?.let { workspaceEnv += "      $it: \${$it}" }
        val moodleLines = mutableListOf(
            "  moodle:",
            "    image: erseco/alpine-moodle:v5.2.3",
            "    ports:",
            "      - \"8080:8080\"",
        )
        if (platform.moodleMaterialEnabled) {
            moodleLines += listOf(
                "    volumes:",
                "      - moodle-html:/var/www/html",
            )
        }
        moodleLines += listOf(
            "    environment:",
            "      DB_TYPE: pgsql",
            "      DB_HOST: postgres",
            "      DB_NAME: \${POSTGRES_DB}",
            "      DB_USER: postgres",
            "      DB_PASS: \${POSTGRES_PASSWORD}",
            "      MOODLE_USERNAME: \${MOODLE_USERNAME}",
            "      MOODLE_PASSWORD: \${MOODLE_PASSWORD}",
            "      MOODLE_SITENAME: \${MOODLE_SITENAME}",
            "    depends_on:",
            "      postgres:",
            "        condition: service_healthy",
            "    networks:",
            "      - academy-net",
        )
        return listOf(
        "services:",
        *moodleLines.toTypedArray(),
        "  workspace:",
        "    build:",
        "      context: ./project",
        "      dockerfile: Dockerfile",
        "    image: cccp-education/academy-workspace:latest",
        "    volumes:",
        "      - \"./project:/workspace\"",
        "    working_dir: /workspace",
        "    environment:",
        *workspaceEnv.toTypedArray(),
        "    depends_on:",
        "      ollama:",
        "        condition: service_started",
        "    networks:",
        "      - academy-net",
        "    profiles:",
        "      - agent",
        "  postgres:",
        "    image: postgres:16",
        "    environment:",
        "      POSTGRES_DB: \${POSTGRES_DB}",
        "      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}",
        "    volumes:",
        "      - postgres-data:/var/lib/postgresql/data",
        "    healthcheck:",
        "      test: [\"CMD-SHELL\", \"pg_isready -U postgres\"]",
        "      interval: 10s",
        "      timeout: 5s",
        "      retries: 5",
        "    networks:",
        "      - academy-net",
        "  ollama:",
        "    image: ollama/ollama",
        "    volumes:",
        "      - ollama-models:/root/.ollama",
        "    ports:",
        "      - \"11434:11434\"",
        "    healthcheck:",
        "      test: [\"CMD\", \"ollama\", \"list\"]",
        "      interval: 30s",
        "      timeout: 10s",
        "      retries: 3",
        "    networks:",
        "      - academy-net",
        "  portainer:",
        "    image: portainer/portainer-ce",
        "    ports:",
        "      - \"9000:9000\"",
        "    volumes:",
        "      - portainer-data:/data",
        "      - \"/var/run/docker.sock:/var/run/docker.sock\"",
        "    networks:",
        "      - academy-net",
        "  moodle-seed:",
        "    image: postgres:16",
        "    restart: \"no\"",
        "    entrypoint: [\"sh\", \"/seed/seed.sh\"]",
        "    environment:",
        "      PGHOST: postgres",
        "      PGDATABASE: \${POSTGRES_DB}",
        "      PGUSER: postgres",
        "      PGPASSWORD: \${POSTGRES_PASSWORD}",
        "    volumes:",
        "      - \"./seed:/seed\"",
        "    depends_on:",
        "      postgres:",
        "        condition: service_healthy",
        "    networks:",
        "      - academy-net",
        *moodleMaterialService(platform).toTypedArray(),
        "",
        "networks:",
        "  academy-net:",
        "    driver: bridge",
        "",
        "volumes:",
        "  postgres-data:",
        "  ollama-models:",
        "  portainer-data:",
        *moodleHtmlVolume(platform).toTypedArray(),
        )
    }

    /**
     * The one-shot `moodle-material` service (ACADEMY-11-4, D-ACADEMY-11-5),
     * declared only when the learner opted into injection — otherwise the
     * scaffold is byte-identical (D-ACADEMY-11-6).
     *
     * It is the exact `moodle-seed` pattern (ACADEMY-6-5): `restart: "no"`,
     * explicit `entrypoint`, `depends_on: moodle: service_healthy`. It shares
     * the `moodle-html` volume so `moosh` bootstraps against the very install
     * the `moodle` service created (verified on the real image, S-016), mounts
     * the staged plan read-write at `/ingest` and the pulled material read-only
     * at `/material`.
     */
    private fun moodleMaterialService(platform: InstallerPlatform): List<String> {
        if (!platform.moodleMaterialEnabled) return emptyList()
        return listOf(
            "  moodle-material:",
            "    image: erseco/alpine-moodle:v5.2.3",
            "    restart: \"no\"",
            "    entrypoint: [\"sh\", \"/ingest/entrypoint.sh\"]",
            "    environment:",
            "      MATERIAL_DIR: /material",
            "    volumes:",
            "      - \"./moodle:/ingest\"",
            "      - \"./material:/material:ro\"",
            "      - moodle-html:/var/www/html",
            "    depends_on:",
            "      moodle:",
            "        condition: service_healthy",
            "    networks:",
            "      - academy-net",
        )
    }

    /** The shared Moodle code tree, declared only when injection is enabled. */
    private fun moodleHtmlVolume(platform: InstallerPlatform): List<String> =
        if (platform.moodleMaterialEnabled) listOf("  moodle-html:") else emptyList()

    /**
     * The API-key **environment variable name** the workspace service receives
     * (ACADEMY-7) — the documented per-provider default, or the learner's
     * override. `null` for the embedded local runtime: no key, no variable.
     * The variable's *value* is never generated (Secrets rule).
     */
    private fun workspaceKeyEnvVar(platform: InstallerPlatform): String? {
        if (!platform.openCodeEnabled) return null
        val documented = ByokProviderCatalog.specFor(platform.openCodeProvider).apiKeyEnvVar
        return platform.openCodeApiKeyEnvVar ?: documented
    }

    /**
     * `.env` body — documents the runtime configuration **names only**; values
     * are provided by the learner at runtime and never committed (Secrets rule,
     * D-ACADEMY-6-5). `POSTGRES_PASSWORD` is intentionally left empty; the BYOK
     * key variable (ACADEMY-7) is documented as a name with no value.
     */
    private fun envBody(platform: InstallerPlatform): List<String> = buildList {
        add("# Academy runtime configuration - names only, values are provided at runtime (never committed)")
        add("POSTGRES_DB=moodle")
        add("POSTGRES_USER=postgres")
        add("POSTGRES_PASSWORD=")
        add("MOODLE_USERNAME=admin")
        add("MOODLE_PASSWORD=")
        add("MOODLE_SITENAME=Academy")
        add("OLLAMA_HOST=http://ollama:11434")
        workspaceKeyEnvVar(platform)?.let { add("$it=") }
    }

    /**
     * Seed entrypoint body (D-ACADEMY-6-6) — the single source of truth shared
     * by every platform. The one-shot `moodle-seed` service runs it on the first
     * `compose up`: it polls until Moodle has created its schema (`mdl_course`)
     * then applies [seedCourseSqlBody]. It never migrates, never deletes.
     *
     * The value of `PGPASSWORD` is read from the environment at runtime — this
     * scaffold embeds the convention only, never a secret.
     */
    private fun seedScriptBody(): List<String> = listOf(
        "#!/bin/sh",
        "# Academy Moodle seed entrypoint - idempotent, data-only (D-ACADEMY-6-6)",
        "set -eu",
        "echo \"[academy] waiting for the Moodle schema (mdl_course)...\"",
        "attempt=0",
        "until psql -tAc \"SELECT to_regclass('public.mdl_course')\" 2>&1 | grep -q mdl_course; do",
        "  attempt=\$((attempt + 1))",
        "  if [ \"\$attempt\" -ge 60 ]; then",
        "    echo \"[academy] Moodle schema not ready after 60 attempts - aborting seed\"",
        "    exit 1",
        "  fi",
        "  sleep 5",
        "done",
        "echo \"[academy] applying data-only course seed...\"",
        "psql -v ON_ERROR_STOP=1 -f /seed/seed-course.sql",
        "echo \"[academy] course seed applied (idempotent)\"",
    )

    /**
     * Minimal course seed SQL (D-ACADEMY-6-6) — **data-only and idempotent**:
     * a single `INSERT ... WHERE NOT EXISTS` keyed by a stable `idnumber`, so
     * running it twice is a no-op. No `DDL`, no `DELETE`, no `UPDATE`.
     */
    private fun seedCourseSqlBody(): List<String> = listOf(
        "-- Academy minimal course seed - data-only, idempotent (D-ACADEMY-6-6)",
        "-- The course lives in the default category (id 1) created by Moodle install.",
        "INSERT INTO mdl_course (",
        "  category, sortorder, fullname, shortname, idnumber, summary, summaryformat,",
        "  format, showgrades, newsitems, startdate, enddate, visible, groupmode,",
        "  groupmodeforce, defaultgroupingid, lang, timecreated, timemodified,",
        "  enablecompletion, showactivitydates, showcompletionconditions, requested",
        ")",
        "SELECT 1, 0, 'Academy - Experimentation Track', 'academy-seed', 'academy-seed',",
        "       'Minimal Moodle course seeded by the academy installer.', 1,",
        "       'topics', 1, 0, 0, 0, 1, 0,",
        "       0, 0, 'en', extract(epoch FROM now())::bigint, extract(epoch FROM now())::bigint,",
        "       1, 1, 1, 0",
        "WHERE NOT EXISTS (",
        "  SELECT 1 FROM mdl_course WHERE idnumber = 'academy-seed'",
        ");",
    )

    private fun StringBuilder.appendComposeScaffold(platform: InstallerPlatform) {
        if (!platform.composeEnabled) return
        appendLine("mkdir -p \"\$APP_DIR\"")
        appendLine("echo \"[academy] writing docker-compose.yml scaffold...\"")
        appendLine("cat > \"\$APP_DIR/docker-compose.yml\" <<'EOF'")
        composeBody(platform).forEach { appendLine(it) }
        appendLine("EOF")
        appendLine("cat > \"\$APP_DIR/.env\" <<'EOF'")
        envBody(platform).forEach { appendLine(it) }
        appendLine("EOF")
        appendLine("mkdir -p \"\$APP_DIR/seed\"")
        appendLine("cat > \"\$APP_DIR/seed/seed.sh\" <<'EOF'")
        seedScriptBody().forEach { appendLine(it) }
        appendLine("EOF")
        appendLine("cat > \"\$APP_DIR/seed/seed-course.sql\" <<'EOF'")
        seedCourseSqlBody().forEach { appendLine(it) }
        appendLine("EOF")
        appendOpenCodeScaffold(platform)
        appendMaterialScaffold(platform)
        appendMoodleMaterialScaffold(platform)
        appendLine("echo \"[academy] compose scaffold written - edit \$APP_DIR/.env and \$APP_DIR/docker-compose.yml before running docker compose up\"")
    }

    /**
     * Writes the learner workspace files (ACADEMY-5) — the generated
     * `Dockerfile`, `opencode.json` and `AGENTS.md` — under `$APP_DIR/project/`,
     * the directory mounted into the workspace container. Only when
     * [InstallerPlatform.openCodeEnabled]; the content is rendered by the pure
     * `education.cccp.academy.opencode` generators (single source shared by
     * every platform, structural parity).
     */
    private fun StringBuilder.appendOpenCodeScaffold(platform: InstallerPlatform) {
        if (!platform.openCodeEnabled) return
        val config = platform.openCodeConfig()
        appendLine("mkdir -p \"\$APP_DIR/project\"")
        appendLine("echo \"[academy] writing the opencode workspace (Dockerfile, opencode.json, AGENTS.md)...\"")
        appendLine("cat > \"\$APP_DIR/project/Dockerfile\" <<'EOF'")
        WorkspaceDockerfileGenerator.render(config).trimEnd().lines().forEach { appendLine(it) }
        appendLine("EOF")
        appendLine("cat > \"\$APP_DIR/project/opencode.json\" <<'EOF'")
        OpenCodeConfigGenerator.render(config).trimEnd().lines().forEach { appendLine(it) }
        appendLine("EOF")
        appendLine("cat > \"\$APP_DIR/project/AGENTS.md\" <<'EOF'")
        LearnerGuideGenerator.render(config).trimEnd().lines().forEach { appendLine(it) }
        appendLine("EOF")
    }

    private fun StringBuilder.appendWindowsComposeScaffold(platform: InstallerPlatform) {
        if (!platform.composeEnabled) return
        appendLine("rem Compose scaffold")
        appendLine("if not exist \"%APP_DIR%\" mkdir \"%APP_DIR%\"")
        appendLine("> \"%APP_DIR%\\docker-compose.yml\" (")
        composeBody(platform).forEach { appendLine("echo $it") }
        appendLine(")")
        appendLine("> \"%APP_DIR%\\.env\" (")
        envBody(platform).forEach { appendLine("echo $it") }
        appendLine(")")
        appendLine("if not exist \"%APP_DIR%\\seed\" mkdir \"%APP_DIR%\\seed\"")
        appendLine("> \"%APP_DIR%\\seed\\seed.sh\" (")
        seedScriptBody().forEach { appendLine("echo ${escapeCmd(it)}") }
        appendLine(")")
        appendLine("> \"%APP_DIR%\\seed\\seed-course.sql\" (")
        seedCourseSqlBody().forEach { appendLine("echo ${escapeCmd(it)}") }
        appendLine(")")
        appendWindowsOpenCodeScaffold(platform)
        appendWindowsMaterialScaffold(platform)
        appendWindowsMoodleMaterialScaffold(platform)
        appendLine("rem Edit %APP_DIR%\\.env and %APP_DIR%\\docker-compose.yml before running docker compose up")
    }

    /**
     * Writes the material requirement guide (ACADEMY-4) under
     * `$APP_DIR/project/MATERIAL.md`, only when the platform declares a
     * requirement ([InstallerPlatform.material]) — the content comes from the
     * pure [education.cccp.academy.material.MaterialGuideGenerator], the single
     * source shared by every platform (structural parity, D-ACADEMY-4-10).
     *
     * It declares the requirement and the frozen mechanism (git pull); it never
     * cites a runnable command that does not exist (BUREAU-3 🔴 À FAIRE, S-012).
     */
    private fun StringBuilder.appendMaterialScaffold(platform: InstallerPlatform) {
        val material = platform.material ?: return
        appendLine("mkdir -p \"\$APP_DIR/project\"")
        appendLine("echo \"[academy] writing the training material requirement (MATERIAL.md)...\"")
        appendLine("cat > \"\$APP_DIR/project/MATERIAL.md\" <<'EOF'")
        MaterialGuideGenerator.render(material).trimEnd().lines().forEach { appendLine(it) }
        appendLine("EOF")
    }

    /**
     * Windows writer of the learner workspace files (ACADEMY-5) — renders the
     * *same* content as the bash heredoc ([appendOpenCodeScaffold]) through the
     * batch `> file (` redirection, so Linux/Windows parity is structural.
     */
    private fun StringBuilder.appendWindowsOpenCodeScaffold(platform: InstallerPlatform) {
        if (!platform.openCodeEnabled) return
        val config = platform.openCodeConfig()
        appendLine("rem opencode workspace (ACADEMY-5)")
        appendLine("if not exist \"%APP_DIR%\\project\" mkdir \"%APP_DIR%\\project\"")
        appendLine("> \"%APP_DIR%\\project\\Dockerfile\" (")
        WorkspaceDockerfileGenerator.render(config).trimEnd().lines().forEach { appendLine("echo ${escapeCmd(it)}") }
        appendLine(")")
        appendLine("> \"%APP_DIR%\\project\\opencode.json\" (")
        OpenCodeConfigGenerator.render(config).trimEnd().lines().forEach { appendLine("echo ${escapeCmd(it)}") }
        appendLine(")")
        appendLine("> \"%APP_DIR%\\project\\AGENTS.md\" (")
        LearnerGuideGenerator.render(config).trimEnd().lines().forEach { appendLine("echo ${escapeCmd(it)}") }
        appendLine(")")
    }

    /**
     * Windows writer of the material requirement guide (ACADEMY-4) — renders the
     * *same* content as the bash heredoc ([appendMaterialScaffold]) through the
     * batch `> file (` redirection, so Linux/Windows parity is structural.
     */
    private fun StringBuilder.appendWindowsMaterialScaffold(platform: InstallerPlatform) {
        val material = platform.material ?: return
        appendLine("rem training material requirement (ACADEMY-4)")
        appendLine("if not exist \"%APP_DIR%\\project\" mkdir \"%APP_DIR%\\project\"")
        appendLine("> \"%APP_DIR%\\project\\MATERIAL.md\" (")
        MaterialGuideGenerator.render(material).trimEnd().lines().forEach { appendLine("echo ${escapeCmd(it)}") }
        appendLine(")")
    }

    /**
     * Writes the Moodle material injection staging (ACADEMY-11-4) under
     * `$APP_DIR/moodle/`, plus the read-only material mount point
     * `$APP_DIR/material/`, only when injection is enabled (D-ACADEMY-11-6).
     *
     * The **generic** entrypoint is always staged; the plan JSON and the
     * plan-driven applicator are staged only when the material actually read a
     * non-empty plan — otherwise the entrypoint prints the explicit degraded
     * message and injects nothing. Content comes from the pure
     * [education.cccp.academy.moodle.MoodleIngestionScriptGenerator] (single
     * source shared by every platform, structural parity).
     */
    private fun StringBuilder.appendMoodleMaterialScaffold(platform: InstallerPlatform) {
        if (!platform.moodleMaterialEnabled) return
        appendLine("mkdir -p \"\$APP_DIR/moodle\"")
        appendLine("mkdir -p \"\$APP_DIR/material\"")
        appendLine("echo \"[academy] writing the Moodle material injection staging (entrypoint, plan, applicator)...\"")
        appendLine("cat > \"\$APP_DIR/moodle/entrypoint.sh\" <<'EOF'")
        MoodleIngestionScriptGenerator.renderEntrypoint().trimEnd().lines().forEach { appendLine(it) }
        appendLine("EOF")
        val plan = platform.moodlePlan?.takeIf { !it.isEmpty } ?: return
        appendLine("cat > \"\$APP_DIR/moodle/plan.json\" <<'EOF'")
        MoodleIngestionScriptGenerator.renderPlanJson(plan).trimEnd().lines().forEach { appendLine(it) }
        appendLine("EOF")
        appendLine("cat > \"\$APP_DIR/moodle/ingest.sh\" <<'EOF'")
        MoodleIngestionScriptGenerator.renderApplicator(plan).trimEnd().lines().forEach { appendLine(it) }
        appendLine("EOF")
    }

    /**
     * Windows writer of the Moodle material injection staging (ACADEMY-11-4) —
     * renders the *same* content as the bash heredoc
     * ([appendMoodleMaterialScaffold]) through the batch `> file (`
     * redirection, so Linux/Windows parity is structural.
     */
    private fun StringBuilder.appendWindowsMoodleMaterialScaffold(platform: InstallerPlatform) {
        if (!platform.moodleMaterialEnabled) return
        appendLine("rem Moodle material injection staging (ACADEMY-11)")
        appendLine("if not exist \"%APP_DIR%\\moodle\" mkdir \"%APP_DIR%\\moodle\"")
        appendLine("if not exist \"%APP_DIR%\\material\" mkdir \"%APP_DIR%\\material\"")
        appendLine("> \"%APP_DIR%\\moodle\\entrypoint.sh\" (")
        MoodleIngestionScriptGenerator.renderEntrypoint().trimEnd().lines()
            .forEach { appendLine("echo ${escapeCmd(it)}") }
        appendLine(")")
        val plan = platform.moodlePlan?.takeIf { !it.isEmpty } ?: return
        appendLine("> \"%APP_DIR%\\moodle\\plan.json\" (")
        MoodleIngestionScriptGenerator.renderPlanJson(plan).trimEnd().lines()
            .forEach { appendLine("echo ${escapeCmd(it)}") }
        appendLine(")")
        appendLine("> \"%APP_DIR%\\moodle\\ingest.sh\" (")
        MoodleIngestionScriptGenerator.renderApplicator(plan).trimEnd().lines()
            .forEach { appendLine("echo ${escapeCmd(it)}") }
        appendLine(")")
    }

    /**
     * Escapes the cmd metacharacters that are special inside a batch
     * `> file (` block: `^` `>` `&` `|` `(` `)`. Required so a line redirecting
     * stderr (`2>&1`) or calling a SQL function (`to_regclass(...)`) is echoed
     * literally by the Windows writer — the caret is consumed by cmd and the
     * written file keeps the original character.
     */
    private fun escapeCmd(line: String): String = line
        .replace("^", "^^")
        .replace(">", "^>")
        .replace("&", "^&")
        .replace("(", "^(")
        .replace(")", "^)")
}